/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package banco.virtual;

import javax.swing.JOptionPane;

/**
 *
 * @author Mathe
 */
public class MenuAddConta extends javax.swing.JDialog {

    /**
     * Creates new form MenuAddConta
     */
    public MenuAddConta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NomeLabel = new javax.swing.JLabel();
        SobrenomeLabel = new javax.swing.JLabel();
        DepositoLabel = new javax.swing.JLabel();
        NomeCampo = new javax.swing.JTextField();
        SobrenomeCampo = new javax.swing.JTextField();
        DepositoCampo = new javax.swing.JTextField();
        TipoLabel = new javax.swing.JLabel();
        TipoBox = new javax.swing.JComboBox<>();
        BotaoOk = new javax.swing.JButton();
        BotaoCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        NomeLabel.setText("Nome:");

        SobrenomeLabel.setText("Sobrenome:");

        DepositoLabel.setText("Depósito Inicial:");

        NomeCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeCampoActionPerformed(evt);
            }
        });

        SobrenomeCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SobrenomeCampoActionPerformed(evt);
            }
        });

        TipoLabel.setText("Tipo de conta");

        TipoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Simples", "Especial", "Poupanca" }));
        TipoBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoBoxActionPerformed(evt);
            }
        });

        BotaoOk.setText("Ok");
        BotaoOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoOkActionPerformed(evt);
            }
        });

        BotaoCancelar.setText("Cancelar");
        BotaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TipoLabel)
                        .addGap(52, 52, 52)
                        .addComponent(TipoBox, 0, 125, Short.MAX_VALUE))
                    .addComponent(DepositoLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NomeLabel)
                            .addComponent(SobrenomeLabel))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SobrenomeCampo)
                            .addComponent(NomeCampo)
                            .addComponent(DepositoCampo, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))))
                .addGap(28, 28, 28)
                .addComponent(BotaoOk, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoCancelar)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomeLabel))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SobrenomeLabel)
                            .addComponent(SobrenomeCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DepositoLabel)
                            .addComponent(DepositoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BotaoCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(BotaoOk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TipoLabel)
                    .addComponent(TipoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NomeCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeCampoActionPerformed

    private void SobrenomeCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SobrenomeCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SobrenomeCampoActionPerformed

    private void TipoBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoBoxActionPerformed

    private void BotaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCancelarActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoCancelarActionPerformed

    private void BotaoOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoOkActionPerformed
        StringBuilder warnings = new StringBuilder();
        String Nome = "", Sobrenome = "", deposito = "";
        double amount = 0;
        
            if(NomeCampo.getText().isEmpty()){ 
                warnings.append("Primeiro nome não pode estar vazio\n");
    }//GEN-LAST:event_BotaoOkActionPerformed
            else {
                Nome = NomeCampo.getText();
            }
            if(SobrenomeCampo.getText().isEmpty()){
                warnings.append("Sobrenome não pode estar vazio\n");
           } else{
                Sobrenome = SobrenomeCampo.getText();
            }
           
           if(DepositoCampo.getText().isEmpty()){
                warnings.append("Valor de deposito não pode estar vazio\n");
           }
           else{
               try{
                   amount = Double.parseDouble(DepositoCampo.getText());
               }
               catch(NumberFormatException ex){
                   warnings.append("Deposito deve ser um numero");
               }
           }
           if (warnings.length() > 0){
               JOptionPane.showMessageDialog(this, warnings.toString(),"Erros de digitação",JOptionPane.WARNING_MESSAGE);
           }
           else{
                   Conta conta = null;
                   
                   if(TipoBox.getSelectedItem().toString() == "Simples"){
                       conta = new Simples(amount);
                   }
                    
                   else if(TipoBox.getSelectedItem().toString() == "Especial"){
                       conta = new Especial(amount);
                   }
                   else if(TipoBox.getSelectedItem().toString() ==  "Poupanca")
                       conta = new Poupanca(amount);
           
           }
            Cliente cliente = new Cliente(Nome, Sobrenome, conta);
            banco.addCliente(cliente);
    }
     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAddConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAddConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAddConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAddConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MenuAddConta dialog = new MenuAddConta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCancelar;
    private javax.swing.JButton BotaoOk;
    private javax.swing.JTextField DepositoCampo;
    private javax.swing.JLabel DepositoLabel;
    private javax.swing.JTextField NomeCampo;
    private javax.swing.JLabel NomeLabel;
    private javax.swing.JTextField SobrenomeCampo;
    private javax.swing.JLabel SobrenomeLabel;
    private javax.swing.JComboBox<String> TipoBox;
    private javax.swing.JLabel TipoLabel;
    // End of variables declaration//GEN-END:variables


